version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environment/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/neko
      - public-data:/neko/public
      - tmp-data:/neko/tmp
      - log-data:/neko/log
    depends_on:
      - db
    environment:
      - EDITOR=vim
    tty: true
    stdin_open: true
  db:
    image: mysql:8.0
    env_file:
      - ./environment/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/neko/public
      - tmp-data:/neko/tmp
    ports:
      - 3001:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: